language: clojure
dist: xenial
sudo: true
branches:
  only:
  - master
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-get update
  - bash etc/ci-setup.sh
install: true
script: eval "$TEST_CMD"
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - IS_RUNNING_ON_TRAVIS=true
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-clojure.git"
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  matrix:
  - TEST_CMD="/tmp/testrunner/bin/run ."
  - TEST_CMD="bash etc/hatchet-test.sh"
