[buildpack]
name = "Clojure"

  [publish.Ignore]
  files = [
    "etc/",
    "spec/",
    "test/",
    ".gitignore",
    ".github/",
    "hatchet.json",
    "hatchet.lock",
    "Gemfile",
    "Gemfile.lock",
]
