#!/usr/bin/env bash

# This gets replaced by bin/compile for DRY purposes.
export LEIN_VERSION="##LEIN_VERSION##"

if [ "$LEIN_DEV" = "" ]; then
  export LEIN_NO_DEV=y
fi

LEIN_JAR=".lein/leiningen-$LEIN_VERSION-standalone.jar"

export JAVA_CMD=${JAVA_CMD:-"java"}
export LEIN_JAVA_CMD=${LEIN_JAVA_CMD:-$JAVA_CMD}

# Prefer JVM_OPTS, but fall back to JAVA_OPTS for compatibility
export JVM_OPTS="${JVM_OPTS:-"$JAVA_OPTS"}"
export LEIN_JVM_OPTS="${LEIN_JVM_OPTS:-$JVM_OPTS} -Dleiningen.original.pwd=$PWD"
export LEIN_HOME="$PWD/.lein"

if [ "$1" == "repl" ]; then
  CLASSPATH=$(lein classpath)
  if [ "$COLUMNS" != "" -a "$LINES" != "" ]; then
    stty columns $COLUMNS
    stty rows $LINES
    exec rlwrap java $LEIN_JVM_OPTS -cp $CLASSPATH clojure.main --repl
  else
    exec java $LEIN_JVM_OPTS -cp $CLASSPATH clojure.main --repl
  fi
else
  TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"
  CLASSPATH="$CLASSPATH:test/:src/:.lein-plugins/*:lib/dev/*:$LEIN_JAR"

  java $LEIN_JVM_OPTS -cp "$CLASSPATH" \
    -Dleiningen.trampoline-file=$TRAMPOLINE_FILE \
    clojure.main -e "(use 'leiningen.core)(-main)" /dev/null $@
  EXIT_CODE=$?

  if [ -r $TRAMPOLINE_FILE ]; then
    TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
    rm $TRAMPOLINE_FILE
    exec sh -c "exec $TRAMPOLINE"
  else
    exit $EXIT_CODE
  fi
fi
